<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Clients\**" />
    <Compile Remove="Views\Workers\**" />
    <Content Remove="Views\Clients\**" />
    <Content Remove="Views\Workers\**" />
    <EmbeddedResource Remove="Views\Clients\**" />
    <EmbeddedResource Remove="Views\Workers\**" />
    <None Remove="Views\Clients\**" />
    <None Remove="Views\Workers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.NetCore" Version="1.9.0" />
    <PackageReference Include="itext7" Version="9.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\" />
  </ItemGroup>

</Project>
